---
# tasks file for openstack-vm

- name: create server
  os_server:
    name: "{{ openstack_vm_name }}"
    flavor_ram: "{{ openstack_vm_memory }}"
    image: "{{ openstack_vm_image }}"
    validate_certs: "{{ openstack_vm_validate_certs }}"
    network: "{{ openstack_vm_network }}"
    key_name: "{{ openstack_vm_key_name }}"
  register: openstack_vm_server

- name: show VM ip
  debug:
    msg: "{{ openstack_vm_instance_ip }}"
